### PR TITLE
Remove Id::Form

### PR DESCRIPTION
**Pull request by craigbrad**
Remove `Id::Form` in order to remove `activemodel` as a dependency. `Id::Form` will be implemented in a new gem of it's own. This will allow the use of Id with rails versions lower than 3.

### CODE REVIEW

**Comment by craigbrad** [comment]
Build is failing as bundler is not compatible with rubygems 2.5.0

**Comment by gavinlaking** [comment]
:+1:

**Comment by marcwinstanley** [comment]
👍

**Comment by purinkle** [comment]
👌

**Pull request merged**
